### ISSUE TITLE
Support testing schema compatibility

### ISSUE THREAD

**Issue by lacarvalho91** [iadvize/sbt-avro#3]
This is a feature request to support testing schema compatibility with schemas in the schema registry.

This would be useful if you wish to have your CI test compatibility of schema changes when PRs are raised/updated.

This would work in a similar way to the `avro:upload` task except it would just be making a different call to the schema registry client.

The behaviour IMO should be that if any of the schemas are incompatible the task should exit with an error.

I think this capability would be a good addition to this plugin.

I will raise a PR for this soon. Let me know what you guys think!

**Comment by jocelyndrean** [comment]
> The behaviour IMO should be that if any of the schemas are incompatible the task should exit with an error.

You're right ! 

Thanks @lacarvalho91 for your contribution, I will review your PR :)

**Comment by lacarvalho91** [comment]
@jocelyndrean thanks!

A bit off topic...but I was wondering if this plugin is/will be released somewhere public? Would be cool if we didn't have to build and publish it ourselves. I can see from `build.sbt` that it is published to your JFrog Artifactory, but I'm unsure if that is accessible for downloads?

**Comment by jocelyndrean** [comment]
We didn't publish yet this plugin somewhere public. Right now, we publish it in our private JFrog Artifactory, so you're not able to download it. You have to publish it locally: `sbt publishLocal`. I'm agree with you, it would be cool if you didn't have to build and publish it yourselves. Added to my todo list.

**Comment by schrepfler** [comment]
Gentle reminder to publish the plugin :).
